### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by agharta83** [agharta83/task-manager#3]
- [ ] Create todo
- [ ] Read todo
- [ ] Update todo
- [ ] Delete todo
- [ ] Create route '/todolist'

- [ ]  Create table in db
- [ ] Create route '/todolist'
